//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WilcoCon.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    public partial class Customer
    {
        public Customer()
        {
            this.Projects = new HashSet<Project>();
        }

        [DisplayName("Customer Id")]
        public int CustomerId { get; set; }


        [DisplayName("First Name")]
        [Required(ErrorMessage = "A First Name is required")]
        public string FirstName { get; set; }

        [DisplayName("Last Name")]
        [Required(ErrorMessage = "A Last Name is required")]
        public string LastName { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "An Email is required")]
        public string Email { get; set; }

        [DisplayName("Phone Number")]
        [Required(ErrorMessage = "A Phone Number is required")]
        public string Phone { get; set; }

        [DisplayName("Payment Terms")]
        [Required(ErrorMessage = "Payment Terms are required")]
        public string PaymentTerms { get; set; }

        [DisplayName("Billing Address")]
        [Required(ErrorMessage = "A Billing Address is required")]
        public string BillingAddress { get; set; }

        public string Notes { get; set; }

        [DisplayName("Company Name")]
        public string CompanyName { get; set; }

        [DisplayName("Billing City")]
        [Required(ErrorMessage = "A Billing City is required")]
        public string BillingCity { get; set; }

        [DisplayName("Billing State")]
        [Required(ErrorMessage = "A Billing State is required")]
        public string BillingState { get; set; }

        [DisplayName("Billing Zip")]
        [Required(ErrorMessage = "A Billing Zip is required")]
        public string BillingZip { get; set; }
    
        public virtual ICollection<Project> Projects { get; set; }
    }
}
