//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace WilcoCon.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Employee
    {
        public Employee()
        {
            this.TimeCards = new HashSet<TimeCard>();
        }

        [DisplayName("Employee Id")]
        public int EmployeeId { get; set; }
        [Required(ErrorMessage = "A SSN is required")]
        public string SSN { get; set; }
        [Required(ErrorMessage = "A Last Name is required")]
        [DisplayName("Last Name")]
        public string LastName { get; set; }
        [DisplayName("First Name")]
        [Required(ErrorMessage = "A First name is required")]
        public string FirstName { get; set; }

        [DisplayName("Street Address")]
        [Required(ErrorMessage = "A Street is required")]
        public string Street { get; set; }

        [Required(ErrorMessage = "A City is required")]
        public string City { get; set; }
        [Required(ErrorMessage = "A State is required")]
        public string State { get; set; }

        [DisplayName("Zip Code")]
        [Required(ErrorMessage = "A Zip Code is required")]
        public int ZipCode { get; set; }

        [DisplayName("Phone Number")]
        [Required(ErrorMessage = "A Phone Number is required")]
        public string TelephoneNumber { get; set; }

        //[Range(typeof(DateTime), "1/1/1880", "1/1/2020")]
        [Required(ErrorMessage = "A DOB is required")]
        public string DOB { get; set; }
        [Required(ErrorMessage = "A Gender is required")]
        public string Gender { get; set; }

        [DisplayName("Marital Status")]
        [Required(ErrorMessage = "A Marital Status is required")]
        public string MaritalStatus { get; set; }

        [DisplayName("Number of Deductions")]
        [Required(ErrorMessage = "A Deduction Count is required")]
        public int NumberOfDeductions { get; set; }

        [DisplayName("EEOCode")]
        [Required(ErrorMessage = "An EEOC Code is required")]
        public int EEOCOde { get; set; }
    
        public virtual ICollection<TimeCard> TimeCards { get; set; }
    }
}
