//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WilcoCon.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class PayScale
    {
        [DisplayName("Payscale Id")]
        public int PayScaleId { get; set; }

        [DisplayName("Basic Hourly Rate")]
        [Required(ErrorMessage = "Basic Hourly Rate is required")]
        public decimal BasicHourlyRate { get; set; }

        [DisplayName("Fringe Benefit Payments")]
        [Required(ErrorMessage = "Fringe Benefit Payments is required")]
        public decimal FringeBenefitPayments { get; set; }

        [DisplayName("Skill Id")]
        public int SkillId { get; set; }

        [DisplayName("Project Id")]
        public int ProjectId { get; set; }
    
        public virtual JobClassification JobClassification { get; set; }
        public virtual Project Project { get; set; }
    }
}
