//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WilcoCon.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Project
    {
        public Project()
        {
            this.PayScales = new HashSet<PayScale>();
            this.TimeCards = new HashSet<TimeCard>();
        }
        [DisplayName("Project Id")]
        public int ProjectId { get; set; }

        [DisplayName("Project Location")]
        [Required(ErrorMessage = "A Project Location is required")]
        public string ProjectLocation { get; set; }

        [DisplayName("Project Description")]
        [Required(ErrorMessage = "A Project Description is required")]
        public string ProjectDescription { get; set; }

        [DisplayName("Distance from Union Hall")]
        [Required(ErrorMessage = "Distance from Union Hall is required")]
        public int DistanceFromUnionHall { get; set; }

        [DisplayName("Project Supervisor")]
        [Required(ErrorMessage = "A Project Supervisor is required")]
        public string ProjectSupervisor { get; set; }

        [DisplayName("Project Number")]
        [Required(ErrorMessage = "A Project Number is required")]
        public string ProjectNumber { get; set; }

        public bool Active { get; set; }

        [DisplayName("Customer Id")]
        public int CustomerId { get; set; }
    
        public virtual ICollection<PayScale> PayScales { get; set; }
        public virtual ICollection<TimeCard> TimeCards { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
