//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WilcoCon.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TimeCard
    {
        [DisplayName("Timecard Id")]
        public int TimeCardId { get; set; }

        [DisplayName("Employee Id")]
        public int EmployeeId { get; set; }

        [DisplayName("Skill Id")]
        public int SkillId { get; set; }

        [DisplayName("Project Id")]
        public int ProjectId { get; set; }

        [DisplayFormat(DataFormatString = "{0:d}")]
        [DisplayName("Date")]
        [Required(ErrorMessage = "A Date is required")]
        public System.DateTime Date { get; set; }

        [DisplayName("Time In")]
        [Required(ErrorMessage = "Time In is required")]
        public System.TimeSpan TimeIn { get; set; }

        
        [DisplayName("Time Out")]
        [Required(ErrorMessage = "Time Out is required")]
        public System.TimeSpan TimeOut { get; set; }

        public virtual Employee Employee { get; set; }
        public virtual JobClassification JobClassification { get; set; }
        public virtual Project Project { get; set; }
    }
}
